-- 코드를 작성해주세요
SELECT FI.ID, FN.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI JOIN FISH_NAME_INFO AS FN
ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE FI.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FI.FISH_TYPE = FISH_TYPE)