-- 코드를 입력하세요
SELECT HISTORY_ID, FLOOR(BASIC_FEE * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM (
    SELECT H.HISTORY_ID, H.DURATION * H.DAILY_FEE AS BASIC_FEE, 
    CASE 
        WHEN H.DURATION >= 90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE('90%') AND CAR_TYPE = '트럭')
        WHEN H.DURATION >= 30 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE('30%') AND CAR_TYPE = '트럭')
        WHEN H.DURATION >= 7 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE('7%') AND CAR_TYPE = '트럭')
        ELSE 0 END DISCOUNT_RATE
    FROM (SELECT H.HISTORY_ID, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION, C.DAILY_FEE
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H JOIN CAR_RENTAL_COMPANY_CAR AS C
          ON C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭'
         ) AS H
    ) AS T
ORDER BY FEE DESC, HISTORY_ID DESC
