WITH CNT AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT, RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID)
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M 
JOIN REST_REVIEW AS R ON M.MEMBER_ID = R.MEMBER_ID
JOIN CNT AS C ON M.MEMBER_ID = C.MEMBER_ID WHERE C.RNK = 1
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT