-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM (SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
      FROM ITEM_INFO AS II LEFT JOIN ITEM_TREE AS IT
      ON II.ITEM_ID = IT.PARENT_ITEM_ID
      WHERE IT.ITEM_ID IS NULL) AS IC
ORDER BY ITEM_ID DESC
